/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package virtual.pet.shelter;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void testPetName() {
        Pets wolf = new Pets("Wolfy", "Sleek white fur with beautiful blue eyes");
        assertEquals("Wolfy", wolf.getName());
    }

    @Test
    void testPetDescription() {
        Pets wolf = new Pets("Wolfy", "Sleek white fur with beautiful blue eyes");
        assertEquals("Sleek white fur with beautiful blue eyes", wolf.getDescription());
    }

    @Test
    void testPetThirst() {
        Pets Hunter = new Pets("Dobby", "Jet black fur with beady brown eyes");
        assertEquals(100, Hunter.getThirst());
    }

    @Test
    void testPetHunger() {
        Pets Bull = new Pets("Bully", "Muscular bull dog with a beige coat");
        assertEquals(100, Bull.getHunger());
    }

    @Test
    void testPetBoredom() {
        Pets rex = new Pets("Rexy", "Cute dalmatian with brown eyes");
        assertEquals(100, rex.getBoredom());
    }

    @Test
    void testPetHealthTick() {

    }

    @Test
    void testAllPetsInShelter() {

    }

    @Test
    void testIntakePet() {

    }

    @Test
    void testAdoption() {

    }

    @Test
    void testFeedPets() {

    }

    @Test
    void testWaterPets() {

    }

    @Test
    void testPlayPet() {
        
    }

    @Test
    void testCageCleanliness() {

    }

    @Test
    void testCleanCage() {

    }
}
